# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: cd app && npm install
#             - run: cd app && npm run build
#             - run: cd app && npm test
# workflows:
#     build-and-test:
#       jobs:
#         - build-and-test
